# Generated by Django 5.1.3 on 2026-09-03 06:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('WALLET_ADMIN_ADJUSTMENT', 'Wallet admin adjustment'), ('ESCROW_HELD', 'Escrow held'), ('ESCROW_RELEASED', 'Escrow released'), ('ESCROW_REFUNDED', 'Escrow refunded'), ('DISPUTE_RESOLVED', 'Dispute resolved')], max_length=30)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_performed', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_targeting', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'common_audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='common_audi_action_b27234_idx')],
            },
        ),
    ]
