# Generated by Django 5.1.3 on 2026-09-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('WALLET_ADMIN_ADJUSTMENT', 'Wallet admin adjustment'), ('ESCROW_HELD', 'Escrow held'), ('ESCROW_RELEASED', 'Escrow released'), ('ESCROW_REFUNDED', 'Escrow refunded'), ('DISPUTE_RESOLVED', 'Dispute resolved'), ('WITHDRAWAL_REVERSED', 'Withdrawal reversed')], max_length=30),
        ),
    ]
