# Generated by Django 5.1.3 on 2026-09-05 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('WALLET_ADMIN_ADJUSTMENT', 'Wallet admin adjustment'), ('ESCROW_HELD', 'Escrow held'), ('ESCROW_RELEASED', 'Escrow released'), ('ESCROW_REFUNDED', 'Escrow refunded'), ('DISPUTE_RESOLVED', 'Dispute resolved'), ('WITHDRAWAL_REVERSED', 'Withdrawal reversed'), ('ACCOUNT_SUSPENDED', 'Account suspended'), ('ACCOUNT_BANNED', 'Account banned'), ('ACCOUNT_REINSTATED', 'Account reinstated'), ('LISTING_SUSPENDED', 'Listing suspended'), ('LISTING_UNSUSPENDED', 'Listing unsuspended'), ('REPORT_RESOLVED', 'Report resolved'), ('REPORT_DISMISSED', 'Report dismissed')], max_length=30),
        ),
    ]
