# Generated by Django 5.2.17 on 2026-10-09 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='plannerearning',
            new_name='economy_pla_planner_39daf0_idx',
            old_name='economy_pl_planner__a2c4d8_idx',
        ),
        migrations.RenameIndex(
            model_name='transactionorder',
            new_name='economy_tra_buyer_i_48195f_idx',
            old_name='economy_tr_buyer_i_0b9d6f_idx',
        ),
        migrations.RenameIndex(
            model_name='transactionorder',
            new_name='economy_tra_planner_c3e148_idx',
            old_name='economy_tr_planner__2f1f9a_idx',
        ),
        migrations.RenameIndex(
            model_name='transactionorder',
            new_name='economy_tra_plan_id_4adbc1_idx',
            old_name='economy_tr_plan_id_8a1b4c_idx',
        ),
    ]
