# Generated by Django 5.1.3 on 2026-09-05 01:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_type', models.CharField(choices=[('USER', 'User'), ('SERVICE', 'Service listing'), ('MESSAGE', 'Chat message')], max_length=10)),
                ('target_id', models.UUIDField()),
                ('reason', models.CharField(choices=[('SPAM', 'Spam'), ('HARASSMENT', 'Harassment or abuse'), ('FRAUD', 'Fraud or scam'), ('PROHIBITED_CONTENT', 'Prohibited content'), ('IMPERSONATION', 'Impersonation'), ('OTHER', 'Other')], max_length=20)),
                ('detail', models.CharField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='OPEN', max_length=10)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.CharField(blank=True, max_length=1000)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_filed', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'moderation_report',
                'abstract': False,
                'indexes': [models.Index(fields=['status', 'created_at'], name='moderation__status_2a84ce_idx'), models.Index(fields=['target_type', 'target_id'], name='moderation__target__dc17d8_idx')],
            },
        ),
    ]
