# Generated by Django 5.1.3 on 2026-09-03 06:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_profile_profileprivacy_block'),
        ('bookings', '0003_alter_booking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='wallet', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'wallet_wallet',
                'constraints': [models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='wallet_balance_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='Escrow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('HELD', 'Held'), ('RELEASED', 'Released'), ('REFUNDED', 'Refunded')], default='HELD', max_length=10)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='escrow', to='bookings.booking')),
            ],
            options={
                'db_table': 'wallet_escrow',
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='escrow_amount_positive')],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('TOKEN_DEPOSIT', 'Token deposit'), ('ESCROW_HOLD', 'Escrow hold'), ('ESCROW_RELEASE', 'Escrow release'), ('ESCROW_REFUND', 'Escrow refund'), ('ADMIN_ADJUSTMENT', 'Admin adjustment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('idempotency_key', models.CharField(blank=True, max_length=100)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='bookings.booking')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='wallet.wallet')),
            ],
            options={
                'db_table': 'wallet_ledger_entry',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['wallet', 'created_at'], name='wallet_ledg_wallet__fa2518_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('wallet', 'idempotency_key'), name='unique_wallet_idempotency_key')],
            },
        ),
    ]
