# Generated by Django 5.2.17 on 2026-10-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_promotional_credits'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='promotionalcredit',
            new_name='wallet_prom_user_id_a2826e_idx',
            old_name='wallet_promo_user_expiry_idx',
        ),
        migrations.RenameIndex(
            model_name='promotionalcredit',
            new_name='wallet_prom_user_id_4e029c_idx',
            old_name='wallet_promo_user_remaining_idx',
        ),
        migrations.AddField(
            model_name='escrow',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='escrow',
            name='promotional_allocations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='escrow',
            name='promotional_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='escrow',
            name='promotional_refunded_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('TOKEN_DEPOSIT', 'Token deposit'), ('ESCROW_HOLD', 'Escrow hold'), ('ESCROW_RELEASE', 'Escrow release'), ('ESCROW_REFUND', 'Escrow refund'), ('ADMIN_ADJUSTMENT', 'Admin adjustment'), ('PLAN_PAYMENT', 'Plan payment'), ('PLAN_REFUND', 'Plan refund'), ('PLANNER_EARNING', 'Planner earning'), ('PLATFORM_FEE', 'Platform fee'), ('EARNINGS_REVERSAL', 'Earnings reversal'), ('GIFT_CREDIT', 'Gift credit'), ('GIFT_DEBIT', 'Gift debit'), ('PROMOTIONAL_CREDIT', 'Promotional credit'), ('PROMOTIONAL_DEBIT', 'Promotional debit'), ('WITHDRAWAL', 'Withdrawal'), ('WITHDRAWAL_REVERSAL', 'Withdrawal reversal')], max_length=30),
        ),
    ]
