# Generated by Django 5.1.15 on 2026-09-14 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_profileprivacy_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role_confirmed',
            field=models.BooleanField(default=True),
        ),
    ]
