# Generated by Django 5.2.17 on 2026-10-08 04:02

import apps.square.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendTree',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=60)),
                ('note', models.CharField(blank=True, max_length=140)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'square_friend_tree',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video')], default='text', max_length=5)),
                ('text', models.CharField(blank=True, max_length=140)),
                ('file', models.FileField(blank=True, upload_to=apps.square.models.status_upload_path)),
                ('duration_seconds', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(default=apps.square.models.default_expiry)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'square_status',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatusReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emoji', models.CharField(max_length=8)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='square.status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'square_status_reaction',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Thought',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=280)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'square_thought',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ThoughtReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emoji', models.CharField(max_length=8)),
                ('thought', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='square.thought')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'square_thought_reaction',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FriendTreeMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='square.friendtree')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'square_friend_tree_member',
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('tree', 'user'), name='unique_tree_member')],
            },
        ),
        migrations.AddIndex(
            model_name='status',
            index=models.Index(fields=['expires_at'], name='square_stat_expires_b0f338_idx'),
        ),
        migrations.AddConstraint(
            model_name='statusreaction',
            constraint=models.UniqueConstraint(fields=('status', 'user'), name='unique_status_reaction'),
        ),
        migrations.AddIndex(
            model_name='thought',
            index=models.Index(fields=['-created_at'], name='square_thought_recent_idx'),
        ),
        migrations.AddConstraint(
            model_name='thoughtreaction',
            constraint=models.UniqueConstraint(fields=('thought', 'user'), name='unique_thought_reaction'),
        ),
    ]
