# Generated by Django 5.2.17 on 2026-10-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('square', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendtreemember',
            name='label',
            field=models.CharField(choices=[('family', 'Family'), ('partner', 'Partner'), ('besties', 'Besties'), ('friends', 'Friends'), ('work', 'Workmates'), ('school', 'Classmates'), ('neighbours', 'Neighbours'), ('acquaintance', 'Acquaintances')], default='friends', max_length=16),
        ),
    ]
