# Generated by Django 5.1.3 on 2026-09-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('FUNDED', 'Funded'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('RELEASED', 'Released'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded'), ('DISPUTED', 'Disputed')], default='PENDING', max_length=20),
        ),
    ]
