# Generated by Django 5.1.15 on 2026-09-07 06:26

import apps.chat.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ImageField(upload_to=apps.chat.models.message_attachment_upload_path)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('size_bytes', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'chat_message_attachment',
                'abstract': False,
            },
        ),
        migrations.RemoveConstraint(
            model_name='message',
            name='message_body_not_empty_unless_deleted',
        ),
        migrations.AddField(
            model_name='message',
            name='has_attachment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('body', ''), _negated=True), ('is_deleted', True), ('has_attachment', True), _connector='OR'), name='message_body_not_empty_unless_deleted_or_has_attachment'),
        ),
        migrations.AddField(
            model_name='messageattachment',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attachment', to='chat.message'),
        ),
    ]
