# Generated by Django 5.2.17 on 2026-10-05 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_group_invites_and_join_requests'),
        ('chat', '0009_rename_member_user_index'),
    ]

    operations = [
    ]
